spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database: h2
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties.hibernate.format_sql: true
  security:
    user:
      name: uno
      password: kim
  data:
    rest:
      base-path: /api
      default-media-type: application/json
management:
  endpoints:
#    TODO: Security vulnerable settings. Must be reviewed
    enabled-by-default: true
    web:
      exposure:
        include: "*"
        exclude: shutdown
logging:
  level:
    root: info
    com.me.sample: debug
